name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Gradle Cache
      id: gradle-cache
      uses: actions/cache@v4
      with:
        path: .gradle-ci
        key: gradle-cache

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        brew update
        brew install cmake conan
        conan --version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build macOS Native Libraries
      run: |
        ./gradlew -Dgradle.user.home=.gradle-ci packageNativeForMacosArm64 packageNativeForMacosX8664 

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-cache
        path: .gradle-ci
        retention-days: 1
        include-hidden-files: true
  build:
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Gradle Cache
      id: gradle-cache
      uses: actions/cache@v4
      with:
        path: .gradle-ci
        key: gradle-cache

    - name: Download macOS prebuilt libraries
      uses: actions/download-artifact@v4
      with:
        name: macos-cache

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build
      run: |
        task=(assemble)
        if [[ "$GITHUB_REF" =~ refs/tags/v* ]] || [ "$GITHUB_REF" = 'refs/heads/main' ]
        then
          task=(mavenCentralDeploy "-PsonatypeUsername=$SONATYPE_USERNAME" "-PsonatypePassword=$SONATYPE_PASSWORD")
        fi
        ./gradlew -Dgradle.user.home=.gradle-ci "${task[@]}"
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
