name: Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: example/web
          target-folder: /
