name: Update Readme

on:
  push:
    tags: [ 'v*.*.*.*' ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: 'true'
    - name: Update Readme
      run: |
        branch='main'
        git checkout "$branch" 
        git pull
        tag="$(git rev-list --tags='v*.*.*.*' --max-count=1)"
        if [ -z "$tag" ]
        then
          echo "No version tag found!" >&2
          exit 1
        fi
        if ! tag="$(git describe --tags "$tag")"
        then
          echo "Tagged commit could not be described!" >&2
          exit 1
        fi
        tag="${tag#v}"
        sed -i -r "s/([:>])[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+([\"<])/\1$tag\2/g" README.md
        git add README.md
        git config --global user.name "GitHub Workflow"
        git config --global user.email "workflow@libdatachannel-java.github.io"
        if git commit -m 'Update versions in README.md'
        then
          git push origin "$branch"
        fi
